//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace ROSNode.Test
{
    /// <summary>
    /// Message interface definition for <c>test_msgs/msg/Strings</c>.
    /// </summary>
    [global::Rosidl.Runtime.TypeSupportAttribute("test_msgs/msg/Strings")]
    internal unsafe partial class Strings : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static string TypeSupportName => "test_msgs/msg/Strings";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__test_msgs__msg__Strings")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="Strings"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='stringValue'>
        /// Originally defined as: <c><![CDATA[string string_value]]></c>
        /// </param>
        /// <param name='stringValueDefault1'>
        /// Originally defined as: <c><![CDATA[string string_value_default1 "Hello world!"]]></c>
        /// </param>
        /// <param name='stringValueDefault2'>
        /// Originally defined as: <c><![CDATA[string string_value_default2 "Hello'world!"]]></c>
        /// </param>
        /// <param name='stringValueDefault3'>
        /// Originally defined as: <c><![CDATA[string string_value_default3 "Hello\"world!"]]></c>
        /// </param>
        /// <param name='stringValueDefault4'>
        /// Originally defined as: <c><![CDATA[string string_value_default4 "Hello'world!"]]></c>
        /// </param>
        /// <param name='stringValueDefault5'>
        /// Originally defined as: <c><![CDATA[string string_value_default5 "Hello\"world!"]]></c>
        /// </param>
        /// <param name='boundedStringValue'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value]]></c>
        /// </param>
        /// <param name='boundedStringValueDefault1'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default1 "Hello world!"]]></c>
        /// </param>
        /// <param name='boundedStringValueDefault2'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default2 "Hello'world!"]]></c>
        /// </param>
        /// <param name='boundedStringValueDefault3'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default3 "Hello\"world!"]]></c>
        /// </param>
        /// <param name='boundedStringValueDefault4'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default4 "Hello'world!"]]></c>
        /// </param>
        /// <param name='boundedStringValueDefault5'>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default5 "Hello\"world!"]]></c>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public Strings(
            string @stringValue = "",
            string @stringValueDefault1 = "Hello world!",
            string @stringValueDefault2 = "Hello'world!",
            string @stringValueDefault3 = "Hello\"world!",
            string @stringValueDefault4 = "Hello'world!",
            string @stringValueDefault5 = "Hello\"world!",
            string @boundedStringValue = "",
            string @boundedStringValueDefault1 = "Hello world!",
            string @boundedStringValueDefault2 = "Hello'world!",
            string @boundedStringValueDefault3 = "Hello\"world!",
            string @boundedStringValueDefault4 = "Hello'world!",
            string @boundedStringValueDefault5 = "Hello\"world!"
        )
        {
            StringValue = @stringValue;
            StringValueDefault1 = @stringValueDefault1;
            StringValueDefault2 = @stringValueDefault2;
            StringValueDefault3 = @stringValueDefault3;
            StringValueDefault4 = @stringValueDefault4;
            StringValueDefault5 = @stringValueDefault5;
            BoundedStringValue = @boundedStringValue;
            BoundedStringValueDefault1 = @boundedStringValueDefault1;
            BoundedStringValueDefault2 = @boundedStringValueDefault2;
            BoundedStringValueDefault3 = @boundedStringValueDefault3;
            BoundedStringValueDefault4 = @boundedStringValueDefault4;
            BoundedStringValueDefault5 = @boundedStringValueDefault5;
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="Strings"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public Strings(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.StringValue = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValue.AsSpan(), textEncoding);
            this.StringValueDefault1 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValueDefault1.AsSpan(), textEncoding);
            this.StringValueDefault2 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValueDefault2.AsSpan(), textEncoding);
            this.StringValueDefault3 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValueDefault3.AsSpan(), textEncoding);
            this.StringValueDefault4 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValueDefault4.AsSpan(), textEncoding);
            this.StringValueDefault5 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.StringValueDefault5.AsSpan(), textEncoding);
            this.BoundedStringValue = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValue.AsSpan(), textEncoding);
            this.BoundedStringValueDefault1 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValueDefault1.AsSpan(), textEncoding);
            this.BoundedStringValueDefault2 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValueDefault2.AsSpan(), textEncoding);
            this.BoundedStringValueDefault3 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValueDefault3.AsSpan(), textEncoding);
            this.BoundedStringValueDefault4 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValueDefault4.AsSpan(), textEncoding);
            this.BoundedStringValueDefault5 = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.BoundedStringValueDefault5.AsSpan(), textEncoding);
        }
        
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string STRING_CONST = "Hello world!"]]></c>
        /// </summary>
        public const string STRING_CONST = "Hello world!";
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValue { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value_default1 "Hello world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValueDefault1 { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value_default2 "Hello'world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValueDefault2 { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value_default3 "Hello\"world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValueDefault3 { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value_default4 "Hello'world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValueDefault4 { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string string_value_default5 "Hello\"world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string StringValueDefault5 { get; set; }
        
        private string __backingField__BoundedStringValue;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValue
        {
            get
            {
                return __backingField__BoundedStringValue;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValue))]
            set
            {
                __backingField__BoundedStringValue = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValue' must be less or equal than 22.");
            }
        }
        
        private string __backingField__BoundedStringValueDefault1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default1 "Hello world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValueDefault1
        {
            get
            {
                return __backingField__BoundedStringValueDefault1;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValueDefault1))]
            set
            {
                __backingField__BoundedStringValueDefault1 = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValueDefault1' must be less or equal than 22.");
            }
        }
        
        private string __backingField__BoundedStringValueDefault2;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default2 "Hello'world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValueDefault2
        {
            get
            {
                return __backingField__BoundedStringValueDefault2;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValueDefault2))]
            set
            {
                __backingField__BoundedStringValueDefault2 = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValueDefault2' must be less or equal than 22.");
            }
        }
        
        private string __backingField__BoundedStringValueDefault3;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default3 "Hello\"world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValueDefault3
        {
            get
            {
                return __backingField__BoundedStringValueDefault3;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValueDefault3))]
            set
            {
                __backingField__BoundedStringValueDefault3 = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValueDefault3' must be less or equal than 22.");
            }
        }
        
        private string __backingField__BoundedStringValueDefault4;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default4 "Hello'world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValueDefault4
        {
            get
            {
                return __backingField__BoundedStringValueDefault4;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValueDefault4))]
            set
            {
                __backingField__BoundedStringValueDefault4 = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValueDefault4' must be less or equal than 22.");
            }
        }
        
        private string __backingField__BoundedStringValueDefault5;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default5 "Hello\"world!"]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string BoundedStringValueDefault5
        {
            get
            {
                return __backingField__BoundedStringValueDefault5;
            }
            [global::System.Diagnostics.CodeAnalysis.MemberNotNullAttribute(nameof(__backingField__BoundedStringValueDefault5))]
            set
            {
                __backingField__BoundedStringValueDefault5 = value.Length <= 22 ? value : throw new global::System.ArgumentException("Size of the array or string 'BoundedStringValueDefault5' must be less or equal than 22.");
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            priv.StringValue.CopyFrom(this.StringValue, textEncoding);
            priv.StringValueDefault1.CopyFrom(this.StringValueDefault1, textEncoding);
            priv.StringValueDefault2.CopyFrom(this.StringValueDefault2, textEncoding);
            priv.StringValueDefault3.CopyFrom(this.StringValueDefault3, textEncoding);
            priv.StringValueDefault4.CopyFrom(this.StringValueDefault4, textEncoding);
            priv.StringValueDefault5.CopyFrom(this.StringValueDefault5, textEncoding);
            priv.BoundedStringValue.CopyFrom(this.BoundedStringValue, textEncoding);
            priv.BoundedStringValueDefault1.CopyFrom(this.BoundedStringValueDefault1, textEncoding);
            priv.BoundedStringValueDefault2.CopyFrom(this.BoundedStringValueDefault2, textEncoding);
            priv.BoundedStringValueDefault3.CopyFrom(this.BoundedStringValueDefault3, textEncoding);
            priv.BoundedStringValueDefault4.CopyFrom(this.BoundedStringValueDefault4, textEncoding);
            priv.BoundedStringValueDefault5.CopyFrom(this.BoundedStringValueDefault5, textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new Strings(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Blittable native structure for <c>test_msgs/msg/Strings</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValue;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value_default1 "Hello world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValueDefault1;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value_default2 "Hello'world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValueDefault2;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value_default3 "Hello\"world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValueDefault3;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value_default4 "Hello'world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValueDefault4;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string string_value_default5 "Hello\"world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString StringValueDefault5;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValue;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default1 "Hello world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValueDefault1;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default2 "Hello'world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValueDefault2;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default3 "Hello\"world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValueDefault3;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default4 "Hello'world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValueDefault4;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string<=22 bounded_string_value_default5 "Hello\"world!"]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CString BoundedStringValueDefault5;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.StringValue);
                __hashCode.Add(this.StringValueDefault1);
                __hashCode.Add(this.StringValueDefault2);
                __hashCode.Add(this.StringValueDefault3);
                __hashCode.Add(this.StringValueDefault4);
                __hashCode.Add(this.StringValueDefault5);
                __hashCode.Add(this.BoundedStringValue);
                __hashCode.Add(this.BoundedStringValueDefault1);
                __hashCode.Add(this.BoundedStringValueDefault2);
                __hashCode.Add(this.BoundedStringValueDefault3);
                __hashCode.Add(this.BoundedStringValueDefault4);
                __hashCode.Add(this.BoundedStringValueDefault5);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::ROSNode.Test.Strings.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Blittable native sequence structure for <c>test_msgs/msg/Strings</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_msgs__rosidl_generator_c", EntryPoint = "test_msgs__msg__Strings__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::ROSNode.Test.Strings.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
