//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace ROSNode.TestİnterfaceFiles
{
    /// <summary>
    /// Unbounded sequences of different types
    /// </summary>
    /// <remarks>
    /// Message interface definition for <c>test_interface_files/msg/UnboundedSequences</c>.
    /// </remarks>
    [global::Rosidl.Runtime.TypeSupportAttribute("test_interface_files/msg/UnboundedSequences")]
    internal unsafe partial class UnboundedSequences : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static string TypeSupportName => "test_interface_files/msg/UnboundedSequences";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__test_interface_files__msg__UnboundedSequences")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="UnboundedSequences"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='boolValues'>
        /// Unbounded sequences of different types
        /// <para>(originally defined as: <c><![CDATA[bool[] bool_values]]></c>)</para>
        /// </param>
        /// <param name='byteValues'>
        /// Originally defined as: <c><![CDATA[uınt8[] byte_values]]></c>
        /// </param>
        /// <param name='charValues'>
        /// Originally defined as: <c><![CDATA[ınt8[] char_values]]></c>
        /// </param>
        /// <param name='float32Values'>
        /// Originally defined as: <c><![CDATA[float32[] float32_values]]></c>
        /// </param>
        /// <param name='float64Values'>
        /// Originally defined as: <c><![CDATA[float64[] float64_values]]></c>
        /// </param>
        /// <param name='int8Values'>
        /// Originally defined as: <c><![CDATA[ınt8[] int8_values]]></c>
        /// </param>
        /// <param name='uint8Values'>
        /// Originally defined as: <c><![CDATA[uınt8[] uint8_values]]></c>
        /// </param>
        /// <param name='int16Values'>
        /// Originally defined as: <c><![CDATA[ınt16[] int16_values]]></c>
        /// </param>
        /// <param name='uint16Values'>
        /// Originally defined as: <c><![CDATA[uınt16[] uint16_values]]></c>
        /// </param>
        /// <param name='int32Values'>
        /// Originally defined as: <c><![CDATA[ınt32[] int32_values]]></c>
        /// </param>
        /// <param name='uint32Values'>
        /// Originally defined as: <c><![CDATA[uınt32[] uint32_values]]></c>
        /// </param>
        /// <param name='int64Values'>
        /// Originally defined as: <c><![CDATA[ınt64[] int64_values]]></c>
        /// </param>
        /// <param name='uint64Values'>
        /// Originally defined as: <c><![CDATA[uınt64[] uint64_values]]></c>
        /// </param>
        /// <param name='stringValues'>
        /// Originally defined as: <c><![CDATA[string[] string_values]]></c>
        /// </param>
        /// <param name='basicTypesValues'>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/BasicTypes[] basic_types_values]]></c>
        /// </param>
        /// <param name='constantsValues'>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/Constants[] constants_values]]></c>
        /// </param>
        /// <param name='defaultsValues'>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/Defaults[] defaults_values]]></c>
        /// </param>
        /// <param name='boolValuesDefault'>
        /// Originally defined as: <c><![CDATA[bool[] bool_values_default [false, true, false]]]></c>
        /// </param>
        /// <param name='byteValuesDefault'>
        /// Originally defined as: <c><![CDATA[uınt8[] byte_values_default [0, 1, 255]]]></c>
        /// </param>
        /// <param name='charValuesDefault'>
        /// Originally defined as: <c><![CDATA[ınt8[] char_values_default [0, 1, 127]]]></c>
        /// </param>
        /// <param name='float32ValuesDefault'>
        /// Originally defined as: <c><![CDATA[float32[] float32_values_default [1125, 0, -1125]]]></c>
        /// </param>
        /// <param name='float64ValuesDefault'>
        /// Originally defined as: <c><![CDATA[float64[] float64_values_default [31415, 0, -31415]]]></c>
        /// </param>
        /// <param name='int8ValuesDefault'>
        /// Originally defined as: <c><![CDATA[ınt8[] int8_values_default [0, 127, -128]]]></c>
        /// </param>
        /// <param name='uint8ValuesDefault'>
        /// Originally defined as: <c><![CDATA[uınt8[] uint8_values_default [0, 1, 255]]]></c>
        /// </param>
        /// <param name='int16ValuesDefault'>
        /// Originally defined as: <c><![CDATA[ınt16[] int16_values_default [0, 32767, -32768]]]></c>
        /// </param>
        /// <param name='uint16ValuesDefault'>
        /// Originally defined as: <c><![CDATA[uınt16[] uint16_values_default [0, 1, 65535]]]></c>
        /// </param>
        /// <param name='int32ValuesDefault'>
        /// Originally defined as: <c><![CDATA[ınt32[] int32_values_default [0, 2147483647, -2147483648]]]></c>
        /// </param>
        /// <param name='uint32ValuesDefault'>
        /// Originally defined as: <c><![CDATA[uınt32[] uint32_values_default [0, 1, 4294967295]]]></c>
        /// </param>
        /// <param name='int64ValuesDefault'>
        /// Originally defined as: <c><![CDATA[ınt64[] int64_values_default [0, 9223372036854775807, -9223372036854775808]]]></c>
        /// </param>
        /// <param name='uint64ValuesDefault'>
        /// Originally defined as: <c><![CDATA[uınt64[] uint64_values_default [0, 1, 18446744073709551615]]]></c>
        /// </param>
        /// <param name='stringValuesDefault'>
        /// Originally defined as: <c><![CDATA[string[] string_values_default ["", "max value", "min value"]]]></c>
        /// </param>
        /// <param name='alignmentCheck'>
        /// Regression test: check alignment of basic field after a sequence field is correct
        /// <para>(originally defined as: <c><![CDATA[ınt32 alignment_check]]></c>)</para>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public UnboundedSequences(
            bool[]? @boolValues = null,
            byte[]? @byteValues = null,
            sbyte[]? @charValues = null,
            float[]? @float32Values = null,
            double[]? @float64Values = null,
            sbyte[]? @int8Values = null,
            byte[]? @uint8Values = null,
            short[]? @int16Values = null,
            ushort[]? @uint16Values = null,
            int[]? @int32Values = null,
            uint[]? @uint32Values = null,
            long[]? @int64Values = null,
            ulong[]? @uint64Values = null,
            string[]? @stringValues = null,
            global::ROSNode.TestİnterfaceFiles.BasicTypes[]? @basicTypesValues = null,
            global::ROSNode.TestİnterfaceFiles.Constants[]? @constantsValues = null,
            global::ROSNode.TestİnterfaceFiles.Defaults[]? @defaultsValues = null,
            bool[]? @boolValuesDefault = null,
            byte[]? @byteValuesDefault = null,
            sbyte[]? @charValuesDefault = null,
            float[]? @float32ValuesDefault = null,
            double[]? @float64ValuesDefault = null,
            sbyte[]? @int8ValuesDefault = null,
            byte[]? @uint8ValuesDefault = null,
            short[]? @int16ValuesDefault = null,
            ushort[]? @uint16ValuesDefault = null,
            int[]? @int32ValuesDefault = null,
            uint[]? @uint32ValuesDefault = null,
            long[]? @int64ValuesDefault = null,
            ulong[]? @uint64ValuesDefault = null,
            string[]? @stringValuesDefault = null,
            int @alignmentCheck = 0
        )
        {
            BoolValues = @boolValues ?? global::System.Array.Empty<bool>();
            ByteValues = @byteValues ?? global::System.Array.Empty<byte>();
            CharValues = @charValues ?? global::System.Array.Empty<sbyte>();
            Float32Values = @float32Values ?? global::System.Array.Empty<float>();
            Float64Values = @float64Values ?? global::System.Array.Empty<double>();
            İnt8Values = @int8Values ?? global::System.Array.Empty<sbyte>();
            Uint8Values = @uint8Values ?? global::System.Array.Empty<byte>();
            İnt16Values = @int16Values ?? global::System.Array.Empty<short>();
            Uint16Values = @uint16Values ?? global::System.Array.Empty<ushort>();
            İnt32Values = @int32Values ?? global::System.Array.Empty<int>();
            Uint32Values = @uint32Values ?? global::System.Array.Empty<uint>();
            İnt64Values = @int64Values ?? global::System.Array.Empty<long>();
            Uint64Values = @uint64Values ?? global::System.Array.Empty<ulong>();
            StringValues = @stringValues ?? global::System.Array.Empty<string>();
            BasicTypesValues = @basicTypesValues ?? global::System.Array.Empty<global::ROSNode.TestİnterfaceFiles.BasicTypes>();
            ConstantsValues = @constantsValues ?? global::System.Array.Empty<global::ROSNode.TestİnterfaceFiles.Constants>();
            DefaultsValues = @defaultsValues ?? global::System.Array.Empty<global::ROSNode.TestİnterfaceFiles.Defaults>();
            BoolValuesDefault = @boolValuesDefault ?? new bool[] { false, true, false };
            ByteValuesDefault = @byteValuesDefault ?? new byte[] { 0, 1, 255 };
            CharValuesDefault = @charValuesDefault ?? new sbyte[] { 0, 1, 127 };
            Float32ValuesDefault = @float32ValuesDefault ?? new float[] { 1125f, 0f, -1125f };
            Float64ValuesDefault = @float64ValuesDefault ?? new double[] { 31415d, 0d, -31415d };
            İnt8ValuesDefault = @int8ValuesDefault ?? new sbyte[] { 0, 127, -128 };
            Uint8ValuesDefault = @uint8ValuesDefault ?? new byte[] { 0, 1, 255 };
            İnt16ValuesDefault = @int16ValuesDefault ?? new short[] { 0, 32767, -32768 };
            Uint16ValuesDefault = @uint16ValuesDefault ?? new ushort[] { 0, 1, 65535 };
            İnt32ValuesDefault = @int32ValuesDefault ?? new int[] { 0, 2147483647, -2147483648 };
            Uint32ValuesDefault = @uint32ValuesDefault ?? new uint[] { 0U, 1U, 4294967295U };
            İnt64ValuesDefault = @int64ValuesDefault ?? new long[] { 0L, 9223372036854775807L, -9223372036854775808L };
            Uint64ValuesDefault = @uint64ValuesDefault ?? new ulong[] { 0UL, 1UL, 18446744073709551615UL };
            StringValuesDefault = @stringValuesDefault ?? new string[] { "", "max value", "min value" };
            AlignmentCheck = @alignmentCheck;
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="UnboundedSequences"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public UnboundedSequences(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.BoolValues = priv.BoolValues.AsSpan().ToArray();
            this.ByteValues = priv.ByteValues.AsSpan().ToArray();
            this.CharValues = priv.CharValues.AsSpan().ToArray();
            this.Float32Values = priv.Float32Values.AsSpan().ToArray();
            this.Float64Values = priv.Float64Values.AsSpan().ToArray();
            this.İnt8Values = priv.İnt8Values.AsSpan().ToArray();
            this.Uint8Values = priv.Uint8Values.AsSpan().ToArray();
            this.İnt16Values = priv.İnt16Values.AsSpan().ToArray();
            this.Uint16Values = priv.Uint16Values.AsSpan().ToArray();
            this.İnt32Values = priv.İnt32Values.AsSpan().ToArray();
            this.Uint32Values = priv.Uint32Values.AsSpan().ToArray();
            this.İnt64Values = priv.İnt64Values.AsSpan().ToArray();
            this.Uint64Values = priv.Uint64Values.AsSpan().ToArray();
        
            this.StringValues = new string[priv.StringValues.Size];
            var StringValues_span = priv.StringValues.AsSpan();
            for (int __i = 0; __i < this.StringValues.Length; __i++)
            {
                this.StringValues[__i] = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(StringValues_span[__i].AsSpan(), textEncoding);
            }
        
            this.BasicTypesValues = new global::ROSNode.TestİnterfaceFiles.BasicTypes[priv.BasicTypesValues.Size];
            var BasicTypesValues_span = priv.BasicTypesValues.AsSpan();
            for (int __i = 0; __i < this.BasicTypesValues.Length; __i++)
            {
                this.BasicTypesValues[__i] = new global::ROSNode.TestİnterfaceFiles.BasicTypes(in BasicTypesValues_span[__i], textEncoding);
            }
        
            this.ConstantsValues = new global::ROSNode.TestİnterfaceFiles.Constants[priv.ConstantsValues.Size];
            var ConstantsValues_span = priv.ConstantsValues.AsSpan();
            for (int __i = 0; __i < this.ConstantsValues.Length; __i++)
            {
                this.ConstantsValues[__i] = new global::ROSNode.TestİnterfaceFiles.Constants(in ConstantsValues_span[__i], textEncoding);
            }
        
            this.DefaultsValues = new global::ROSNode.TestİnterfaceFiles.Defaults[priv.DefaultsValues.Size];
            var DefaultsValues_span = priv.DefaultsValues.AsSpan();
            for (int __i = 0; __i < this.DefaultsValues.Length; __i++)
            {
                this.DefaultsValues[__i] = new global::ROSNode.TestİnterfaceFiles.Defaults(in DefaultsValues_span[__i], textEncoding);
            }
        
            this.BoolValuesDefault = priv.BoolValuesDefault.AsSpan().ToArray();
            this.ByteValuesDefault = priv.ByteValuesDefault.AsSpan().ToArray();
            this.CharValuesDefault = priv.CharValuesDefault.AsSpan().ToArray();
            this.Float32ValuesDefault = priv.Float32ValuesDefault.AsSpan().ToArray();
            this.Float64ValuesDefault = priv.Float64ValuesDefault.AsSpan().ToArray();
            this.İnt8ValuesDefault = priv.İnt8ValuesDefault.AsSpan().ToArray();
            this.Uint8ValuesDefault = priv.Uint8ValuesDefault.AsSpan().ToArray();
            this.İnt16ValuesDefault = priv.İnt16ValuesDefault.AsSpan().ToArray();
            this.Uint16ValuesDefault = priv.Uint16ValuesDefault.AsSpan().ToArray();
            this.İnt32ValuesDefault = priv.İnt32ValuesDefault.AsSpan().ToArray();
            this.Uint32ValuesDefault = priv.Uint32ValuesDefault.AsSpan().ToArray();
            this.İnt64ValuesDefault = priv.İnt64ValuesDefault.AsSpan().ToArray();
            this.Uint64ValuesDefault = priv.Uint64ValuesDefault.AsSpan().ToArray();
        
            this.StringValuesDefault = new string[priv.StringValuesDefault.Size];
            var StringValuesDefault_span = priv.StringValuesDefault.AsSpan();
            for (int __i = 0; __i < this.StringValuesDefault.Length; __i++)
            {
                this.StringValuesDefault[__i] = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(StringValuesDefault_span[__i].AsSpan(), textEncoding);
            }
        
            this.AlignmentCheck = priv.AlignmentCheck;
        }
        
        
        /// <summary>
        /// Unbounded sequences of different types
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[bool[] bool_values]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public bool[] BoolValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt8[] byte_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public byte[] ByteValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt8[] char_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public sbyte[] CharValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[float32[] float32_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public float[] Float32Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[float64[] float64_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public double[] Float64Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt8[] int8_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public sbyte[] İnt8Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt8[] uint8_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public byte[] Uint8Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt16[] int16_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public short[] İnt16Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt16[] uint16_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public ushort[] Uint16Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt32[] int32_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int[] İnt32Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt32[] uint32_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public uint[] Uint32Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt64[] int64_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public long[] İnt64Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt64[] uint64_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public ulong[] Uint64Values { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string[] string_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string[] StringValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/BasicTypes[] basic_types_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::ROSNode.TestİnterfaceFiles.BasicTypes[] BasicTypesValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/Constants[] constants_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::ROSNode.TestİnterfaceFiles.Constants[] ConstantsValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[test_interface_files/msg/Defaults[] defaults_values]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::ROSNode.TestİnterfaceFiles.Defaults[] DefaultsValues { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[bool[] bool_values_default [false, true, false]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public bool[] BoolValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt8[] byte_values_default [0, 1, 255]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public byte[] ByteValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt8[] char_values_default [0, 1, 127]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public sbyte[] CharValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[float32[] float32_values_default [1125, 0, -1125]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public float[] Float32ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[float64[] float64_values_default [31415, 0, -31415]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public double[] Float64ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt8[] int8_values_default [0, 127, -128]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public sbyte[] İnt8ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt8[] uint8_values_default [0, 1, 255]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public byte[] Uint8ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt16[] int16_values_default [0, 32767, -32768]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public short[] İnt16ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt16[] uint16_values_default [0, 1, 65535]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public ushort[] Uint16ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt32[] int32_values_default [0, 2147483647, -2147483648]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int[] İnt32ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt32[] uint32_values_default [0, 1, 4294967295]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public uint[] Uint32ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[ınt64[] int64_values_default [0, 9223372036854775807, -9223372036854775808]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public long[] İnt64ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uınt64[] uint64_values_default [0, 1, 18446744073709551615]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public ulong[] Uint64ValuesDefault { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[string[] string_values_default ["", "max value", "min value"]]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public string[] StringValuesDefault { get; set; }
        
        /// <summary>
        /// Regression test: check alignment of basic field after a sequence field is correct
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[ınt32 alignment_check]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int AlignmentCheck { get; set; }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            priv.BoolValues.CopyFrom(this.BoolValues);
            priv.ByteValues.CopyFrom(this.ByteValues);
            priv.CharValues.CopyFrom(this.CharValues);
            priv.Float32Values.CopyFrom(this.Float32Values);
            priv.Float64Values.CopyFrom(this.Float64Values);
            priv.İnt8Values.CopyFrom(this.İnt8Values);
            priv.Uint8Values.CopyFrom(this.Uint8Values);
            priv.İnt16Values.CopyFrom(this.İnt16Values);
            priv.Uint16Values.CopyFrom(this.Uint16Values);
            priv.İnt32Values.CopyFrom(this.İnt32Values);
            priv.Uint32Values.CopyFrom(this.Uint32Values);
            priv.İnt64Values.CopyFrom(this.İnt64Values);
            priv.Uint64Values.CopyFrom(this.Uint64Values);
            
            priv.StringValues = new global::Rosidl.Runtime.Interop.CStringSequence(this.StringValues.Length);
            var StringValues_span = priv.StringValues.AsSpan();
            for (int __i = 0; __i < this.StringValues.Length; __i++)
            {
                StringValues_span[__i].CopyFrom(this.StringValues[__i], textEncoding);
            }
            
            priv.BasicTypesValues = new global::ROSNode.TestİnterfaceFiles.BasicTypes.PrivSequence(this.BasicTypesValues.Length);
            var BasicTypesValues_span = priv.BasicTypesValues.AsSpan();
            for (int __i = 0; __i < this.BasicTypesValues.Length; __i++)
            {
                this.BasicTypesValues[__i].WriteTo(ref BasicTypesValues_span[__i], textEncoding);
            }
            
            priv.ConstantsValues = new global::ROSNode.TestİnterfaceFiles.Constants.PrivSequence(this.ConstantsValues.Length);
            var ConstantsValues_span = priv.ConstantsValues.AsSpan();
            for (int __i = 0; __i < this.ConstantsValues.Length; __i++)
            {
                this.ConstantsValues[__i].WriteTo(ref ConstantsValues_span[__i], textEncoding);
            }
            
            priv.DefaultsValues = new global::ROSNode.TestİnterfaceFiles.Defaults.PrivSequence(this.DefaultsValues.Length);
            var DefaultsValues_span = priv.DefaultsValues.AsSpan();
            for (int __i = 0; __i < this.DefaultsValues.Length; __i++)
            {
                this.DefaultsValues[__i].WriteTo(ref DefaultsValues_span[__i], textEncoding);
            }
            
            priv.BoolValuesDefault.CopyFrom(this.BoolValuesDefault);
            priv.ByteValuesDefault.CopyFrom(this.ByteValuesDefault);
            priv.CharValuesDefault.CopyFrom(this.CharValuesDefault);
            priv.Float32ValuesDefault.CopyFrom(this.Float32ValuesDefault);
            priv.Float64ValuesDefault.CopyFrom(this.Float64ValuesDefault);
            priv.İnt8ValuesDefault.CopyFrom(this.İnt8ValuesDefault);
            priv.Uint8ValuesDefault.CopyFrom(this.Uint8ValuesDefault);
            priv.İnt16ValuesDefault.CopyFrom(this.İnt16ValuesDefault);
            priv.Uint16ValuesDefault.CopyFrom(this.Uint16ValuesDefault);
            priv.İnt32ValuesDefault.CopyFrom(this.İnt32ValuesDefault);
            priv.Uint32ValuesDefault.CopyFrom(this.Uint32ValuesDefault);
            priv.İnt64ValuesDefault.CopyFrom(this.İnt64ValuesDefault);
            priv.Uint64ValuesDefault.CopyFrom(this.Uint64ValuesDefault);
            
            priv.StringValuesDefault = new global::Rosidl.Runtime.Interop.CStringSequence(this.StringValuesDefault.Length);
            var StringValuesDefault_span = priv.StringValuesDefault.AsSpan();
            for (int __i = 0; __i < this.StringValuesDefault.Length; __i++)
            {
                StringValuesDefault_span[__i].CopyFrom(this.StringValuesDefault[__i], textEncoding);
            }
            
            priv.AlignmentCheck = this.AlignmentCheck;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new UnboundedSequences(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Unbounded sequences of different types
        /// </summary>
        /// <remarks>
        /// Blittable native structure for <c>test_interface_files/msg/UnboundedSequences</c>.
        /// </remarks>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Unbounded sequences of different types
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[bool[] bool_values]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.BooleanSequence BoolValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt8[] byte_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt8Sequence ByteValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt8[] char_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int8Sequence CharValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[float32[] float32_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.FloatSequence Float32Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[float64[] float64_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.DoubleSequence Float64Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt8[] int8_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int8Sequence İnt8Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt8[] uint8_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt8Sequence Uint8Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt16[] int16_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int16Sequence İnt16Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt16[] uint16_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt16Sequence Uint16Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt32[] int32_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int32Sequence İnt32Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt32[] uint32_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt32Sequence Uint32Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt64[] int64_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int64Sequence İnt64Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt64[] uint64_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt64Sequence Uint64Values;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string[] string_values]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CStringSequence StringValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[test_interface_files/msg/BasicTypes[] basic_types_values]]></c>
            /// </summary>
            public global::ROSNode.TestİnterfaceFiles.BasicTypes.PrivSequence BasicTypesValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[test_interface_files/msg/Constants[] constants_values]]></c>
            /// </summary>
            public global::ROSNode.TestİnterfaceFiles.Constants.PrivSequence ConstantsValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[test_interface_files/msg/Defaults[] defaults_values]]></c>
            /// </summary>
            public global::ROSNode.TestİnterfaceFiles.Defaults.PrivSequence DefaultsValues;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[bool[] bool_values_default [false, true, false]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.BooleanSequence BoolValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt8[] byte_values_default [0, 1, 255]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt8Sequence ByteValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt8[] char_values_default [0, 1, 127]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int8Sequence CharValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[float32[] float32_values_default [1125, 0, -1125]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.FloatSequence Float32ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[float64[] float64_values_default [31415, 0, -31415]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.DoubleSequence Float64ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt8[] int8_values_default [0, 127, -128]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int8Sequence İnt8ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt8[] uint8_values_default [0, 1, 255]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt8Sequence Uint8ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt16[] int16_values_default [0, 32767, -32768]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int16Sequence İnt16ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt16[] uint16_values_default [0, 1, 65535]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt16Sequence Uint16ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt32[] int32_values_default [0, 2147483647, -2147483648]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int32Sequence İnt32ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt32[] uint32_values_default [0, 1, 4294967295]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt32Sequence Uint32ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[ınt64[] int64_values_default [0, 9223372036854775807, -9223372036854775808]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.Int64Sequence İnt64ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[uınt64[] uint64_values_default [0, 1, 18446744073709551615]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.UInt64Sequence Uint64ValuesDefault;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[string[] string_values_default ["", "max value", "min value"]]]></c>
            /// </summary>
            public global::Rosidl.Runtime.Interop.CStringSequence StringValuesDefault;
            
            /// <summary>
            /// Regression test: check alignment of basic field after a sequence field is correct
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[ınt32 alignment_check]]></c>
            /// </remarks>
            public int AlignmentCheck;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.BoolValues);
                __hashCode.Add(this.ByteValues);
                __hashCode.Add(this.CharValues);
                __hashCode.Add(this.Float32Values);
                __hashCode.Add(this.Float64Values);
                __hashCode.Add(this.İnt8Values);
                __hashCode.Add(this.Uint8Values);
                __hashCode.Add(this.İnt16Values);
                __hashCode.Add(this.Uint16Values);
                __hashCode.Add(this.İnt32Values);
                __hashCode.Add(this.Uint32Values);
                __hashCode.Add(this.İnt64Values);
                __hashCode.Add(this.Uint64Values);
                __hashCode.Add(this.StringValues);
                __hashCode.Add(this.BasicTypesValues);
                __hashCode.Add(this.ConstantsValues);
                __hashCode.Add(this.DefaultsValues);
                __hashCode.Add(this.BoolValuesDefault);
                __hashCode.Add(this.ByteValuesDefault);
                __hashCode.Add(this.CharValuesDefault);
                __hashCode.Add(this.Float32ValuesDefault);
                __hashCode.Add(this.Float64ValuesDefault);
                __hashCode.Add(this.İnt8ValuesDefault);
                __hashCode.Add(this.Uint8ValuesDefault);
                __hashCode.Add(this.İnt16ValuesDefault);
                __hashCode.Add(this.Uint16ValuesDefault);
                __hashCode.Add(this.İnt32ValuesDefault);
                __hashCode.Add(this.Uint32ValuesDefault);
                __hashCode.Add(this.İnt64ValuesDefault);
                __hashCode.Add(this.Uint64ValuesDefault);
                __hashCode.Add(this.StringValuesDefault);
                __hashCode.Add(this.AlignmentCheck);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::ROSNode.TestİnterfaceFiles.UnboundedSequences.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Unbounded sequences of different types
        /// </summary>
        /// <remarks>
        /// Blittable native sequence structure for <c>test_interface_files/msg/UnboundedSequences</c>.
        /// </remarks>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("test_interface_files__rosidl_generator_c", EntryPoint = "test_interface_files__msg__UnboundedSequences__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::ROSNode.TestİnterfaceFiles.UnboundedSequences.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
